version: '3.8'

services:
  app:
    container_name: agent-sales-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network
    env_file:
      - .env
    # volumes: // only on dev env
      # - .:/usr/src/app
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    tty: true

  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: always
    ports:
      - '27018:27017' 
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - '6380:6379' # HostPort:ContainerPort
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
