apiVersion: v1
kind: Secret
metadata:
  name: agent-sales-secrets
type: Opaque
stringData:
  DB_URI: {{ .Values.envSecrets.DB_URI }}
  REDIS_HOST: {{ .Values.envSecrets.REDIS_HOST }}
  JWT_SECRET: {{ .Values.envSecrets.JWT_SECRET }}
