apiVersion: v1
kind: Service
metadata:
  name: agent-sales-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: agent-sales-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
